name: Do git pull in Google Cloud
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd /home/ottoj/git/AG_discord_bot/;git fetch --all;git pull origin main --ff-only; sudo systemctl restart ag_bot
