name: Copy DC bot to Ubuntu VM
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy file to Ubuntu VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "alvaraalto.py"
          target: "/home/opc/dc_bot"
        - name: executing remote ssh commands using password

      - uses: appleboy/ssh-action@v0.1.7
      - name: Restart Service
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: systemctl --user stop dc_bot; systemctl --user start dc_bot
